### ISSUE TITLE
How can I see the HTML code?

### ISSUE THREAD

**Issue by saltnlight5** [jichu4n/asciidoclive#1]
Hi, Is there way I can copy the HTML output code that rendered on the right side of your asciiDocLive editor?

**Comment by jichu4n** [comment]
Thanks for filing an issue! This isn't supported right now, but I'll definitely look into it ASAP.

**Comment by jichu4n** [comment]
Added support for

- Viewing output HTML (Menu -> Settings -> Show Output HTML)
- Downloading output HTML (Menu -> Save -> Download Output HTML)

Marking this as closed, but please let me know if you find any issues.
