### ISSUE TITLE
Save / Open document from local file system

### ISSUE THREAD

**Issue by cmoulliard** [jichu4n/asciidoclive#3]
I would like to suggest to add a new feature offering the possibility to save / open document locally (as proposed by stackedit - https://github.com/benweet/stackedit/)

Here is the stackedit dev doc explaining how Files are managed  : https://github.com/benweet/stackedit/blob/master/doc/developer-guide.md#developer-guide

**Comment by jichu4n** [comment]
Thanks for the suggestion!

Just added support for saving the document locally (Menu -> Save -> Download Source). Still working on opening local files.

**Comment by jichu4n** [comment]
Implemented opening local files (Menu -> Open -> Local File).

I'm going to close this, but please let me know if you find any issues.
